### ISSUE TITLE
Release 0.2.1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1141]
Tracking bug for 0.2.1.

We have a number of fixes that we should get out in a 0.2.1 release.

Missing Cherry Picks

- [x] #1170 Cherry pick of  #1144 Upgrade Jupyter images to v0.2.1
- [x] #1147 Upgrade Central UI image (and tag it v0.2.1)
- [x] #1150 Cherry-pick fix to Katib Ambassador routes.
- [x] #1189 Merge in the latest scripts
- [x] #1152 Don't check in boot strap vendor
- [x] #1114 PyTorch job should include the full prototype
- [x] Fix for #1139 Fix permissions to work with private GCR
- [ ] #1188 Use PV by default for /home/jovyan

**Comment by jlewi** [comment]
I brought up a cluster with commit 6b14d8e76b585befaf74d0b9ef096b937a2a4089

Verified
 
  - GKE deployment scripts worked
  - Central UI shows link to JupyterHub

**Comment by jlewi** [comment]
Cut RC
https://github.com/kubeflow/kubeflow/releases/tag/v0.2.1-rc.0

But its missing a couple fixes.

**Comment by jlewi** [comment]
It looks like GKE isn't using PV by default.
Created #1187; we should probably just make it the default.

**Comment by jlewi** [comment]
v0.2.1 has been pushed.

Docs have been updated.

Only thing left to do is publicize it.
