### ISSUE TITLE
Create 0.3. Release

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1541]
This is the tracking bug for cutting a 0.3 release.

[30 Remaining P1s](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Akubeflow+label%3Aarea%2F0.3.0+label%3Apriority%2Fp1+)

Blocking issues

- [x] Create updated images for Katib; #1604
       * ~~#1400 update Katib releaser~~
- [x] Update image for Central UI #1435 
- [x] Update TFJob image #1599
- [x] Update PyTorch image #1600
- [x] Update Jupyter notebook images #1601
- [x] Update Chainer image kubeflow/chainer-operator#25
- [x] Update Seldon #1598
- [x] Update KubeBench images #1602

Testing
- [x] Run tests periodically on the release branch #1603 

Missing Cherrypicks
- [x] #1632 Update Katib components to include CRD.

At a minimum we should manually deploy the RC and verify

* Can spawn a notebook in Jupyter
* CentralDashboard UI links work
* Katib can be deployed
* Can run of the Katib examples.

**Comment by jlewi** [comment]
Looks like we have a bunch of work to do to get images built for all our different components. 

Here's what I think we should do

1. We should start running our image release workflows using prow; this will allow us to get signal on presubmit & postsubmit on which image workflows are broken
1. The first step is to run all the relevant image release workflows on postsubmit 

   * #1565 adds centraldashboard and jupyter images
   * We should follow #1565 with PRs adding chainer, pytorch, and TFServing
   * TFJob would be nice but we'd have to define a release workflow first

1. Once the above is completed we can identify images that are broken and create and assign issues to
    fix them

   * We can enable the tests in the presubmit to verify that the PR fixes

1. We can update the postsubmits to start pushing the images to gcr.io/kubeflow-images-public
    * This way those images will be immediately available to be used in our components

See #1575 centraldashboard image releaser isn't working.

**Comment by richardsliu** [comment]
Release candidate created: https://github.com/kubeflow/kubeflow/releases/tag/4e7f4ed

**Comment by jlewi** [comment]
Katib images now being built on postsubmit. We have updated images
gcr.io/kubeflow-images-public/katib

Need a PR to update the ksonnet component on the release branch.

**Comment by jlewi** [comment]
#1597 will update Katib images on master; Will need to cherry pick it on v0.3 branch.
