### ISSUE TITLE
[Dashboard v1][Tracker] Bug Bash 1 issues

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#2777]
## About
This is a parent tracker issue for all Dashboard work that comes as a result of the Kubeflow bug bash

## Issues to Tackle:
- [x] Privacy link in the sidebar doesn't point anywhere - [PR: #2786]
- [x] Style Guide for all framed apps to comply with Kubeflow Design - #2775 [PR: #2878]
- [x] Namespace selector should only show on pages that actually support the behavior - [PR: #2788]

---
/assign @avdaredevil @prodonjs 
/priority p1
/area centraldashboard
/area front-end
