### ISSUE TITLE
[Dashboard v1][Tracker] Update Central Dashboard documentation

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#2836]
Add sections explaining:

- [x] High-level application architecture view
- [x] Authoring/running tests.
- [x] Information about the build/release process

**Comment by avdaredevil** [comment]
Hey @prodonjs, Can you edit this issue to include `[Tracker]` and `[Dashboard v1]`?
