### ISSUE TITLE
[CentralDashboard] Match UX Specifications [Tracker]

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/kubeflow#3154]
Implement changes to match [UX specifications](https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZYbjDGnaKqEC/files/MCEJu8Y2hyDScZFDtRjUQxaOQcsK82q9efU)

- [x] 1. Correct header behavior to show as white when viewing an iframed application 
- [x] 2. Move and restyle namespace selector
- [x] 3. Update sidebar link and card content
- [x] 4. Update font and spacing for cards
- [x] 5. Update hover/active styles for sidebar
- [x] 6. Move horizontal view tabs from header to content section.

/area front-end
/area centraldashboard
/priority p1
/cc @ajayalfred 
/assign @avdaredevil 
/assign @prodonjs

**Comment by avdaredevil** [comment]
Could you please add `[Tracker]` To the title? And thanks for making this, I'll tag respective PRs to this

**Comment by prodonjs** [comment]
Sure I noticed that in the past but I didn't know it's significance. You
may be able to change the issue title but I'm not sure.
