### ISSUE TITLE
kfctl for codelabs polishing

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/kubeflow#3604]
A few rough edges to smooth out based on codelabs/qwiklabs feedback:

- [ ] #3550 Add argument for suppressing warnings, either as a flag or the ability to specify log level
- [ ] #3549 Remove references to ~/.kube/config file during `kfctl init`, since there is no expectation of an existing cluster
- [ ] #3586 Handle cloud-endpoints error thrown towards the end of `kfctl apply`
- [ ] Handle all 3 auth types without throwing errors (warnings are fine): OAuth, basic, or none (port-forwarding)

**Comment by Sygyzmundovych** [comment]
It seems like another issue not covered by any of the above:
`kfctl apply platform`
ends at
`WARN[0269] Updating basic auth login is failed, trying to create one: secrets "kubeflow-login" not found  filename="gcp/gcp.go:1387"`
and not with
`"KUBECONFIG context kubeflow-qwiklab is created,"` as described in https://google.qwiklabs.com/focuses/5169?parent=catalog#step5

As well no "In Deployment Manager, two deployment objects will appear:
kubeflow-qwiklab-storage
kubeflow-qwiklab" as described in the tutorial's step.

Is this tutorial worth 9 credits at this stage?

**Comment by jbottum** [comment]
@texasmichelle is this for the GCP platform or other platforms too?
