### ISSUE TITLE
Release cut v0.6.2

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3860]
We need to cut minor release v0.6.2 which include latest UIs and minor bug fixes.
Please comment below if your PR should be cherry-picked to v0.6.2.

[P0s](https://github.com/issues?utf8=%E2%9C%93&q=org%3Akubeflow+label%3Apriority%2Fp0+project%3Akubeflow%2F5+is%3Aopen+)

**Comment by johnugeorge** [comment]
https://github.com/kubeflow/kubeflow/pull/3792

**Comment by kimwnasptd** [comment]
#3845

**Comment by jlewi** [comment]
@johnugeorge Can you please create a cherry-pick of #3792 onto the v0.6-branch

@kimwnasptd Are we automatically building a docker image from the jupyter web app on post submit? If we do have an image built can you update the manifests to use it and then cherry pick that onto the v0.6-branch of kubeflow/manifests

**Comment by johnugeorge** [comment]
> @johnugeorge Can you please create a cherry-pick of #3792 onto the v0.6-branch

/cc @krishnadurai 
> 
> @kimwnasptd Are we automatically building a docker image from the jupyter web app on post submit? If we do have an image built can you update the manifests to use it and then cherry pick that onto the v0.6-branch of kubeflow/manifests

**Comment by yanniszark** [comment]
https://github.com/kubeflow/kubeflow/pull/3857
https://github.com/kubeflow/kubeflow/pull/3760

**Comment by johnugeorge** [comment]
Also, I see that the deployment manifests still use rc images https://github.com/kubeflow/manifests/commit/e448fba3f6672f2f98abafb5d991475531cb8e20

 0.6 Release images are not created? 
@richardsliu

**Comment by jlewi** [comment]
Here's a list of scenarios related to the multi-user UI changes and functionality that we should verify are working before finalizing the RC
https://github.com/kubeflow/kubeflow/issues/3437#issuecomment-520674809
/cc @kunmingg @avdaredevil

**Comment by krishnadurai** [comment]
@johnugeorge Just waiting for the release 0.6 and master branch conflict to get resolved. My cherry-pick is showing a conflict.

**Comment by avdaredevil** [comment]
Replied @ #3437

**Comment by yanniszark** [comment]
#3885 is also vital.

**Comment by jlewi** [comment]
#3893 is tracking verifying the multi-user scenarios are working correctly

**Comment by krishnadurai** [comment]
@kunmingg 
Branches master and 0.6 release are out of sync. Looks like some of the commits in 0.6 branch are not in master.

Master:
https://github.com/kubeflow/kubeflow/commits/master/bootstrap/config/kfctl_k8s_istio.yaml

0.6 release:
https://github.com/kubeflow/kubeflow/commits/v0.6.2-rc.0/bootstrap/config/kfctl_k8s_istio.yaml

Here's the commit I'm looking to cherry-pick:
https://github.com/kubeflow/kubeflow/commit/2f94612ce62eaa2a5ba23da7c0515b65dac380a7
I’ll need your help in resolving this.

**Comment by yanniszark** [comment]
Since this is a release centered around multi-user, https://github.com/kubeflow/kubeflow/issues/3553 should be resolved as well, to enable multi-user functionality in environments other than GCP (eg Azure, AWS, On-Prem).

cc @Jeffwan for AWS

**Comment by jlewi** [comment]
@gabrielwen Here's the release guide
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md

One thing we should add to the release guide is making sure repos listed in KfDef specs are pinned to the proper commits.

**Comment by gabrielwen** [comment]
Let's track on every items:
- [ ] Cherrypick #3792 @johnugeorge @krishnadurai 
- [ ] Cherrypick #3845 @kimwnasptd 
- [ ] Cherrypick tracking #3868 @yanniszark 
- [ ] Cherrypick fixes in #3437 @kunmingg 
- [ ] Cherrypick #3885 @yanniszark 
- [ ] Feature tracking #3893 @kunmingg 
- [ ] [kfctl_k8s_istio out of sync](https://github.com/kubeflow/kubeflow/issues/3860#issuecomment-521117431) @kunmingg @richardsliu @krishnadurai 
- [ ] Tracking #3553 @yanniszark 

Please ping back on this issue once you finish cherrypick.

**Comment by yanniszark** [comment]
@gabrielwen the following PRs should also be in the release:

- Parameterize userid header and prefix in manifets:

**Comment by gabrielwen** [comment]
> @gabrielwen the following PRs should also be in the release:
> 
> * Parameterize userid header and prefix in manifests: [kubeflow/manifests#274](https://github.com/kubeflow/manifests/pull/274)
> * Add multi user identity awareness to existing_arrikto using the above pr: #3904

Updated, please ping back once you finish the cherrypick :)

**Comment by jlewi** [comment]
I've started this doc to use to test things out
http://bit.ly/2ZgOE1v

@krishnadurai @yanniszark @Jeffwan I'd suggest using that doc and adding sections for the situations you care about.

**Comment by jlewi** [comment]
@krishnadurai at @yanniszark How's it going for your platforms?

For GCP, I will retest after kubeflow/manifests#294 is merged tomorrow. Using the new 0.6.2 RC1

**Comment by Jeffwan** [comment]
@jlewi Can you help look at #3895 #3877 ?

**Comment by krishnadurai** [comment]
@jlewi I'll have a run through the demo script today and see what scenarios are applicable and working with kfctl_k8s_istio.yaml.

**Comment by yanniszark** [comment]
@jlewi I encountered the following issue:

* The notebook uses the Pipeline Python DSL to deploy a Pipeline.
* The Pipeline uses the image generated by Fairing in the previous step.
* That image uses a GCP secret, which is mounted using the command `gcp.use_gcp_secret('user-gcp-sa')`
* The secret lives in the user's namespace (profile namespace) while the pipeline lives in the kubeflow namespace.
* That means the pipeline can't execute, since the secret is in another namespace.

Ideas?

**Comment by yanniszark** [comment]
@gabrielwen https://github.com/kubeflow/manifests/issues/296 has to be resolved before any PRs are merged in v0.6-branch.
Essentially, right now, tests on v0.6-branch are broken, so I can't merge kubeflow/manifests#274

**Comment by jlewi** [comment]
@yanniszark I'm not sure I understand the DSL issue.

A user is running their notebook in namespace kubeflow-${USER}. They submit a pipeline which will run in namespace kubeflow.

So if they configure it to use secret ${SECRET} then the pipeline should be looking for that secret in namespace kubeflow so as long as that secret still exists in namespace kubeflow it should work right?

**Comment by gabrielwen** [comment]
Including #3982 3982

**Comment by jlewi** [comment]
Looks like there has been a fair amount of testing of kfctl v0.6.2-rc2 in http://bit.ly/2ZgOE1v..

Are there any issues finalizing **kfctl v0.6.2**? I'm explicitly trying to separate out the kfctl binary from the KFDef configs.

**Comment by Jeffwan** [comment]
@jlewi can you help approve this one? https://github.com/kubeflow/kubeflow/pull/3895
It's config changes and I want to pin to 0.6.2 later once it's merged.

**Comment by yanniszark** [comment]
I will run the whole example today, now that all the commits are in, and confirm.

**Comment by yanniszark** [comment]
> A user is running their notebook in namespace kubeflow-${USER}. They submit a pipeline which will run in namespace kubeflow.
> So if they configure it to use secret ${SECRET} then the pipeline should be looking for that secret in namespace kubeflow so as long as that secret still exists in namespace kubeflow it should work right?

@jlewi I see that the kfctl GCP code is creating the secret in the kubeflow namespace.
This seems weird to me, as it is putting a user's secret in a place where everyone can use it.

In this particular example though, the secret isn't used at all by the pipeline.
Removing the line that applies the secret to the pipeline makes it succeed.
Should we edit the example to remove that line?

**Comment by jlewi** [comment]
Closing this issue because we have cut 0.6.2
