### ISSUE TITLE
v0.7.0 Release Checklist

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/kubeflow#4249]
P0 issues list: https://github.com/issues?utf8=%E2%9C%93&q=org%3Akubeflow+label%3Apriority%2Fp0+project%3Akubeflow%2F22+is%3Aopen+

- [x] App instance manifests (https://github.com/kubeflow/manifests/issues/489)
- [x] Cut release branch for kubeflow/manifests
- [x] Merge Kfctl upgrades PR
- [x] Migrate kftcl to kubeflow/kfctl
- [x] Cut release branch for kubeflow/kubeflow
- [x] Cut release branch for kubeflow/kfctl
- [x] Make sure periodic tests are running against release branches
- [x] Create initial RC

**Comment by jlewi** [comment]
Demo script for release.
http://bit.ly/demo-v0-7

**Comment by jlewi** [comment]
Here are the issues that I think have changes that will impact kubeflow/manifsts

- [ ] kubeflow/kfserving#399 - will require update to KFServing manifest
- [ ] kubeflow/kubeflow#3822 - will require updating profile controller manifest
- [ ] kubeflow/kubeflow#3703 - KFDef specs need to be updated to use v1beta1
- [ ] Updates to application CRs

I'm not sure we should wait for all the changes to go in before cutting the release branch. I think we should do that sooner and then cherry-pick changes.

**Comment by jlewi** [comment]
Here's the plan as discussed in the KF meeting today

* We will wait for application CRs but then cut kubeflow/manifests v0.7-branch but no later than tomorrow
* kubeflow/kubeflow should be ready to cut
* For kfctl we are still waiting for a bunch of changes and then we will sync the code to kubeflow/kfctl

**Comment by johnugeorge** [comment]
- [ ] https://github.com/kubeflow/kubeflow/issues/4231  Adding Katib label to all Kubeflow namespaces

**Comment by krishnadurai** [comment]
Here are some PRs which we are looking to include for 0.7:

Including Dex Manifests:

- [ ] Upgrade Cert Manager kubeflow/manifests#369 kubeflow/manifests#362
- [ ] Upgrade Istio to 1.3.1 - Makes K8s 1.13+ necessary kubeflow/manifests#413
- [ ] Include Ambassador OIDC - @yanniszark will soon raise a PR with the manifest

**Comment by jlewi** [comment]
@krishnadurai Do we really need to upgrade ISTIO 1.3.1 now? That feels pretty risky to me to be incorporating that big of a change this late in the release cycle.

**Comment by krishnadurai** [comment]
@jlewi I understand this concern. We can wait for the Istio upgrade and make changes where required for the dex configs to work with the present configuration of Istio.

**Comment by jlewi** [comment]
Here's the current status/plan

* Get fixes for all P0s in the [kanban board](https://github.com/orgs/kubeflow/projects/22?card_filter_query=label%3Apriority%2Fp0) merged and cherrypicked to correct branch by EOD today

* Cut an RC tomorrow with all the P0 fixes.

* Test and validate the candidate for the rest of the week. Finalize the RC on Friday.

* We are tracking P0s on the [Kanban board](https://github.com/orgs/kubeflow/projects/22?card_filter_query=label%3Apriority%2Fp0)

Fix and PR management

* Any release blocking issue should be P0 and tagged into the kanban board
* Issues shouldn't be closed until the fix has made it into an RC and the fix has been verified with the RC

**Comment by krishnadurai** [comment]
@jlewi There are 2 things which are required for 0.7 and are:
1. Modifications to Dex configuration to make it seamless as tracked by this [comment](https://github.com/kubeflow/manifests/issues/267#issuecomment-545361761). We are looking to add a KfDef (kubeflow/manifests#560) for our on-premise clusters. I'll take ownership of the testing required here.
2. As discussed, KFServing release seems to be blocked on the Istio upgrade (kubeflow/manifests#413). KFServing team has accepted to help me test the new Istio version with Kubeflow components.

I'm keen on getting these in within this week for the release.

Both of these issues should not block any of the testing required for v0.7.0. 

/cc @animeshsingh @ellis-bigelow @jinchihe @hougangliu @johnugeorge @yanniszark

**Comment by animeshsingh** [comment]
@krishnadurai should DEX be an optional install? Not everyone standing up Kubeflow will be configuring auth/authz at first go?

Also any particular reason we decided to stick 1.1.6? Or it was just a matter of tIming? We need minimum 1.1.7 in KFServing

**Comment by krishnadurai** [comment]
> @krishnadurai should DEX be an optional install? Not everyone standing up Kubeflow will be configuring auth/authz at first go?

Dex is an optional install. This is unrelated to KFServing.

> Also any particular reason we decided to stick 1.1.6? Or it was just a matter of tIming? We need minimum 1.1.7 in KFServing

This was due to timing.

**Comment by krishnadurai** [comment]
>     2. As discussed, KFServing release seems to be blocked on the Istio upgrade ([kubeflow/manifests#413](https://github.com/kubeflow/manifests/pull/413)). KFServing team has accepted to help me test the new Istio version with Kubeflow components.

Update: KFServing release is no longer blocked on Istio upgrade to 1.3.1. It should work with 1.1.6. Release is not blocked on Istio 1.3.1 upgrade.

**Comment by jlewi** [comment]
Here's the current status of things

* I think the only known issue is kubeflow/kubeflow#4415 which is only affecting clusters in which user identity is unknown
* We'd like to have passing greens in our E2E tests
 
   * Basic auth [grid](https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master) - should hopefully be fixed on master and pass in the next run
   * It looks like the [kfctl_existing tests are failing](https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-master)  kubeflow/kfctl/issues/60

**Comment by jlewi** [comment]
kubeflow/kubeflow#4435  
was just merged 

I think all fixes are in and we just need another kfctl RC.

**Comment by Jeffwan** [comment]
The plan looks good to me. AWS side doesn't have any pending changes for 0.7 release.

**Comment by jlewi** [comment]
I tested GCP basic auth with

kubeflow/kubeflow - v0.7.0-rc.7-3-g8dbde9d8
kubeflow/manifests - v0.7.0-rc.2-19-g317c0d8

I was able to successfully deploy and run the xgboost synthetic example

**Comment by jlewi** [comment]
Docs are updated.

Anything else to do before closing this out?

**Comment by richardsliu** [comment]
Should we leave this open until kfctl is cut?

**Comment by animeshsingh** [comment]
@jlewi do we claim Istio 1.3.1 support- even if its not the default in this release?

**Comment by jlewi** [comment]
@animeshsingh I don't think we should claim that since we haven't test it.

**Comment by animeshsingh** [comment]
That's my impression as well - @krishnadurai ?

**Comment by krishnadurai** [comment]
@animeshsingh @jlewi we should not announce 1.3.1 since I think it might not add value to this release and is not tested thoroughly yet. I've opened #4480 to start work on promoting 1.3.1 as the primary installation.

**Comment by jlewi** [comment]
@richardsliu by cut kfctl you mean cut a v0.7 branch on kubeflow/kfctl ?
