### ISSUE TITLE
Notebooks WG Roadmap for 1.4

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#5978]
Lets use this issue to discuss on what we would like to work on for 1.4

These are the following things I'll be working on:
- [ ] Adding e2e tests for the web apps #5960 
- [x] Upgrading the Angular framework of the web apps #5525 
- [ ] Define a generic Viewer CRD that we could use for use cases like TensorBoard, a PVCViewer etc https://github.com/kubeflow/pipelines/issues/5681
- [x] Improve the storage API of the Notebooks web app https://github.com/kubeflow/kubeflow/issues/5971
- [x] Improve the automatic scale-to-zero/culling mechanism we have for Notebooks https://github.com/kubeflow/kubeflow/issues/5128
- [ ] Investigate the performance issues of the web apps #5201 

Feel free to also add things that you would like to work on, or that you would like to see!
cc @yanniszark @StefanoFioravanzo @elikatsis @thesuperzapper @DavidSpek @saffaalvi @JessicaBarh @wg102 @ca-scribner @jbottum

**Comment by DavidSpek** [comment]
@kimwnasptd The [i18n PR](https://github.com/kubeflow/kubeflow/pull/5880) has been fixed to address the CI failing. After a conflict is solved I'll review it, but need some help with merging it. Once that is done, I will fix [my existing PR](https://github.com/kubeflow/kubeflow/pull/5805) for the Angular upgrade.

**Comment by ca-scribner** [comment]
Thanks @kimwnasptd, this feels like a good set of priorities.  Automated scaling (#5128) and web app performance (#5201) would both be huge wins for 1.4 imo

**Comment by DavidSpek** [comment]
From @thesuperzapper and I:

- [ ] Rewrite the Notebook Spawner to make it more configurable and easier to use
- [ ] Automatic image building and caching as part of the spawning workflow

Things I want to look at (maybe not all for 1.4):

- [ ] Fix resolution scaling issues of the web apps
- [ ] More integration between the web apps (launch a tensorboard from the JWA using the PVC of a notebook)
- [ ] Ability to take volume snapshots and a web app to manage them (possibly recurring snapshots with a cron job) (already mostly done for personal version of the VWA)
- [ ] Extend snapshot capabilities to include taking snapshots of entire pods/notebooks
- [ ] Namespace isolated metrics dashboards using Grafana (and associated integrations or we app)
- [ ] Rewrite the Central Dashboard in Angular so it is the same as the other web apps
- [ ] More granular permission control and profile spec to enhance namespace sharing (and create a "project" concept)
- [ ] A user settings page for things like (Git) SSH keys, registry credentials, namespace sharing (and user permissions, similar to GitHub/GitLab)
- [ ] A web app for serving dashboards using r-shiny, Dash, Flask, etc (related to the Viewer CRD)
- [ ] Add the ability to easily share dashboards or KFServing endpoints outside Kubeflow and to non-Kubeflow users (with an OIDC group permissiong for example)

I'll probably add more items once I remember them.

**Comment by kimwnasptd** [comment]
@DavidSpek the above ideas sound interesting! Can you also ensure that you'll create issues for these, so that we can go through the technical details and evaluate which of these we should support within the WG?

Especially for the first two points we will need to first evaluate:
1. what's going to be the required effort
2. what are the technical details and designs
3. what documentation will need to come along
4. what testing will need to be added. Especially for the rewrite of the current web app

**Comment by wg102** [comment]
Statcan has a few things we would want to upstream and include in 1.4
- [ ] I18n for Central Dashboard (Related to https://github.com/kubeflow/kubeflow/issues/5858)
- [ ] Add fonts as assets for central Dashboard (similar to https://github.com/kubeflow/kubeflow/pull/5691)
- [ ] Manage contributors for all namespaces (would allow UI for https://github.com/kubeflow/kubeflow/issues/4569)
- [ ] Environment Variable to set a notebook default language (related to having i18n as a whole, the variable can be used to start notebooks in the preferred language, if available)
- [ ]  CWA: Notebook Volume Management : Would add features to the Volume table for a more friendly management. Block user of the delete option if the volume is used etc. See https://github.com/StatCan/kubeflow/issues/48 for details

**Comment by thesuperzapper** [comment]
@kimwnasptd re improvements to the scale-down of inactive notebooks: 

We need to make sure the method we choose supports all possible (and future) web IDEs. I think there is only __one way__ to do this __generically__, that is, to wrap the IDE's interface in an IFRAME, which picks up when a user moves their mouse/interacts with the UI, and use this info to decide if the user is currently "active".

After an IDE becomes "inactive", we could use some combination of the following to decide if we should actually pause the notebook:
* CPU/RAM (+ possibly GPU) utilisation (to detect long-running training jobs)
* Send an email to the user with a link to "extend the session by X hours" (similar to how colaboratory works)

**Comment by DavidSpek** [comment]
@thesuperzapper It might also be nice to allow users to specify the estimated duration of the job they are running in the notebook, giving them assurance that the notebook will not be stopped in that period (+ some grace period afterwards of course). This is a much easier approach to implement, and will give users some peace of mind that their job will not get stopped halfway.

**Comment by blairdrummond** [comment]
> @kimwnasptd re improvements to the scale-down of inactive notebooks:
> 
> We need to make sure the method we choose supports all possible (and future) web IDEs. I think there is only **one way** to do this **generically**, that is, to wrap the IDE's interface in an IFRAME, which picks up when a user moves their mouse/interacts with the UI, and use this info to decide if the user is currently "active".

Do you think it would be better to impose the responsibility upon the application itself instead? While the idea of having the functionality be totally generic would be a huge plus, there might be more flexibility if, instead, the containers were able to provide their own API for this. For instance a few possible methods could be

```
GET  /suspend_api/suspend_enabled: {true,false}
GET  /suspend_api/requested_grace_period: int     # seconds
GET  /suspend_api/seconds_idle: int
POST /suspend_api/pre_suspend_hook     # call some custom stuff before suspending!
POST /suspend_api/post_suspend_hook    # call some custom stuff after suspending!
```

As a user, I'd want a simple way to turn off the suspend behavior. For example, some of our users use the `/proxy/$port` functionality in jupyterlab to prototype web applications, which they might leave up for days on a small machine. We probably could handle this via a kubeflow UI configuration too, but this might give the application more freedom to decide how to handle suspend

**Comment by DavidSpek** [comment]
@blairdrummond With `application` are you referring to the notebook server instance or the Jupyter Web App? Or would it be in the notebook CR? One downside of allowing users to completely disable culling, is that it might get overused by users defeating most of the purpose of culling idle notebook servers.

**Comment by kimwnasptd** [comment]
@thesuperzapper @blairdrummond @DavidSpek thank you for providing more details, but lets not discuss this in the general tracking issue.

@thesuperzapper please open a distinct issue for this so we can evaluate and discuss the technical details there. If the direction makes sense we can then add that issue here.
