### ISSUE TITLE
Support IAP on GKE

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#60]
When Kubeflow is deployed on GKE it should be easy to configure it to setup IAP to secure remote access to Kubeflow services.
  
- [x] Ksonnet manifests for setting up ingress and other resources
- [x] Docs explaining how to enable IAP
- [x] Use Cloud Endpoints (or some other proxy) to validate JWT and reject traffic that bypassed IAP
    * Blocked by #104 - Can't connect to Jupyter Kernel using sidecar

Here are issues that need to be fixed to use Envoy as a proxy that handles JWT verification
- [x] istio/proxy#941 -Need support for ES256 algorithm which is what IAP uses
- [x] istio/proxy#939 - Need to support headers used by IAP
- [X] istio/proxy#929 - Envoy proxy needs to support rejecting all requests without valid JWT credentials
- [x] istio/proxy#930 - Need to support JWT validation without breaking GCP health checking
     - We can work around this just by having 2 envoy proxies in sequence 
     - both can be running in the same pod

**Comment by jlewi** [comment]
So I have a prototype of enabling IAP https://github.com/jlewi/kubeflow/tree/iap. The one issue I'm hitting is that the proxy doing IAP validation doesn't seem to reject traffic that didn't go through IAP.

In this implementation a sidecar in the JupyterHub pod validates the incoming request and reject it if it didn't go through IAP or the JWT isn't valid.

One question I have is how can we configure JupyterHub to use the identity in the JWT but not verify it? It looks like there's a [JWTAuthenticator](https://github.com/mogthesprog/jwtauthenticator) but I don't actually want to authenticate it since the request was already authenticated in the side car.

Is there an easy way to tell JupyterHub to get identity from the JWT but not authenticate it?

/cc @yuvipanda @mogthesprog @foxish

**Comment by mogthesprog** [comment]
I’m on mobile and out at the moment. But IIRC IAP sends some special headers X-Goog-User or something, so you could maybe use the Remote-User Authenticator for jupyter hub which takes the name of the user header as configuration? I can have another nose for the links when I get home. 

That should do what you need on then jupyterhub end I believe.

**Comment by jlewi** [comment]
@mogthesprog Thanks for the quick response let me try that out.

**Comment by jlewi** [comment]
That worked thank you very much. I just had to configure the JupyterHub config as follows

```
c.JupyterHub.authenticator_class ='jhub_remote_user_authenticator.remote_user_auth.RemoteUserAuthenticator'
c.RemoteUserAuthenticator.header_name = 'x-goog-authenticated-user-email'
```

**Comment by mogthesprog** [comment]
Awesome! :) Glad it worked!

Yeah there are a couple of headers forwarded by IAP. I’ll have to check if there’s one that contains a signed JWT and maybe that can be used to by the jwtauthenticator.

**Comment by jlewi** [comment]
Yup there is see [here](https://cloud.google.com/iap/docs/signed-headers-howto). 

In our case, I think its safe to use `x-goog-authenticated-user-{email,id}` because we're relying on the sidecar to ensure traffic went through IAP and IAP will strip out any user supplied `x-goog-*` headers.

**Comment by jlewi** [comment]
The envoy issues have been addressed so we should be unblocked.

**Comment by jlewi** [comment]
I believe this is the docker file I used
https://github.com/jlewi/proxy/blob/iap/docker/Dockerfile.kubeflow

But its probably unnecessary to build our own Docker image if they already built one with the changes.
If not I think this is there release script.
https://github.com/jlewi/proxy/blob/iap/script/release-docker
