### ISSUE TITLE
Umbrella Issue: Porting Kubeflow to IBM Power (ppc64le)

### ISSUE THREAD

**Issue by lehrig** [kubeflow/kubeflow#6684]
/kind feature

Enable builds & releases for IBM Power (ppc64le architecture). This proposal was presented [with these slides ](https://github.com/kubeflow/kubeflow/files/9862922/2022-10-25.Porting.Kubeflow.to.IBM.Power.pdf) at the [2022-10-25 Kubeflow community call](https://bit.ly/kf-meeting-notes) with positive community feedback.

**Why you need this feature:**
- Widen scope of possible on-premises deployments (vanilla Kubernetes & OpenShift on Power)
- More general independence regarding processor architecture (x86, ppc64le, arm, …)

**Describe the solution you'd like:**
1. Upstream build & release integration for ppc64le
2. An external, public webpage with ppc64le-specific manifests, install guides, and end-to-end examples provided by IBM

We currently plan to divide 1. into two phases: (1) low-hanging "easy" integrations where no or minor code changes are needed, (2) more complex integrations where external dependencies to python wheels exist. Currently, we believe (1) can be within the Kubeflow 1.7 release scope and help setting a baseline for (2). Below is a detailed overview of each required integration, including links to associated PRs if those already exist.

**Phase 1 Integrations (Kubeflow 1.7 scope)**
- [ ] Admission Webhook: https://github.com/kubeflow/kubeflow/pull/6650
- [ ] Cache
- [ ] Central Dashboard
- [ ] Jupyter Web App: https://github.com/kubeflow/kubeflow/pull/6650
- [ ] Katib
- [ ] KServe: Agent & Controller: https://github.com/kserve/kserve/pull/2476
- [ ] KServer: Models Web App: https://github.com/kserve/models-web-app/pull/45
- [ ] Notebook Controller
- [ ] Profiles + KFAM: https://github.com/kubeflow/kubeflow/pull/6650
- [ ] Tensorboard Controller
- [ ] Tensorboard Web App: https://github.com/kubeflow/kubeflow/pull/6650
- [ ] Training Operator: https://github.com/kubeflow/training-operator/pull/1674
- [ ] Volumes Web App: https://github.com/kubeflow/kubeflow/pull/6650

**Phase 2 Integrations (Post Kubeflow 1.7 scope)**
- [ ] Pipelines
- [ ] KServe: Storage Initializer

**External-facing Webpage (Post Kubeflow 1.7 scope)**
- [ ] Manifests
- [ ] Install guides
- [ ] End-to-end Examples

**Comment by kimwnasptd** [comment]
Thanks for creating this tracking issue @lehrig!

I'm onboard with adding support for ppc64le, since this will greatly help KF adoption. The proposed plan makes sense.

My initial question at this time is whether we need to build different executables for this platform, which means we need a new set of images. I see in the PRs that the only needed change is to actually not set a specific platform, but I might be missing something.

Could you provide some more context on this one?

**Comment by lehrig** [comment]
@kimwnasptd, thanks for your support!

There are essentially 2 options for for publishing images:

1. **Multi-arch images**, where we publish only 1 "virtual" image with support for multiple architectures. A `pull` command will then only fetch the concrete container image for the required platform. To do so, I'd recommend using `buildx` (e.g., see https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) because it is easier to use / more automated compared to manually creating a container manifest file for multiple architectures.
2. **Separate images** per architecture.

IMO 1. should be the preferred solution. A challenge here will be that builds over all Kubeflow components are quite inconsistent. For example, some projects already use `buildx` while some others don't. I'd opt for implementing more consistency in the scope of this endeavor, e.g., by migrating builds towards `buildx` where feasible. My team would be willing to drive this, if this sounds good.

**Comment by kimwnasptd** [comment]
@lehrig I agree with the first approach as well, if it's viable to avoid having multiple manifests.

Docker's `buildx` seems promising. I hadn't used it the past though, but it seems quite straight forward. I don't have a hard preference on using `buildx` as long as we don't lock in ourselves and end up with Dockerfiles that need specific Docker features and can only be build with `docker`.

**Comment by lehrig** [comment]
As wished by @kimwnasptd, quoting myself from https://github.com/kubeflow/kubeflow/pull/6650#discussion_r1029586906 to clarify how we envision multi-arch builds:

> Yes, it's good to let GO determine the arch, so we don't have to maintain an arch list explicitly here or wrap around boiler-plate code with arch-specific if/else statements.
> 
> Instead, we now shift the control which arch is actually build to the build system. If doing nothing special, the arch of the build machine is simply used (and as Kubeflow is currently build on amd64, we are backwards-compatible to the current behavior).
> 
> In further PRs, we will additionally modify docker-based builds using buildx, where you can, for instance, do something like this:
> `docker buildx build --platform linux/amd64,linux/ppc64le ... `
> 
> Here, docker will automatically run actually 2 builds: one for amd64 and one for ppc64le. When coming to above GO-code, GO will acknowledge the external platform configuration and build it correctly. In case no native hardware is available for the given platform, docker will emulate the architecture using QEMU - so you can also build for different archs on amd64.
> 
> The final outcome is a single multi-arch image with support of all archs listed in Docker's platform statement.

**Comment by kimwnasptd** [comment]
@lehrig @adilhusain-s! the first image in this repo with support for ppc64le is up! 🎉 

https://hub.docker.com/layers/kubeflownotebookswg/notebook-controller/80f695e/images/sha256-2870219816f6be1153ca97eb604b4f20393c34afdb4eade83f0966ccf90f8018?context=explore

**Comment by kimwnasptd** [comment]
@lehrig @pranavpandit1 @adilhusain-s I realized that right now we've only implemented the logic for using `docker buildx` only for the Actions that run when a PR is merged, and not when a PR is opened. 

Realized that the Centraldashboard image was not getting build, even though the PR checks were green:
28a24ffb170769a228d46a19892f7420b22a0816
74f020e0d9c3f58712a3b466f9d1bb86c4607beb
65e41bf28b8e79be4e1f822afe56e218c69db8a1

We fixed the issue for this in https://github.com/kubeflow/kubeflow/pull/6960, but we should be able to catch errors for the multi-arch build when a PR is opened as well.

The fix should be straightforward. We'll just need to use the same build command in both types of actions. Referencing the relevant parts in one:
https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/centraldb_intergration_test.yaml#L24
https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/centraldb_docker_publish.yaml#L37-L41

**Comment by kimwnasptd** [comment]
Do you have cycles to help with this effort?

**Comment by lehrig** [comment]
@kimwnasptd let me confirm with the team but I think we can handle it

**Comment by pranavpandit1** [comment]
> @kimwnasptd let me confirm with the team but I think we can handle it

@kimwnasptd: Thanks for all the inputs, 
we have started looking into the required changes and will keep everyone updated once we start raising PRs for the same.

**Comment by lehrig** [comment]
Note I updated the main description by adding a phase for Kubeflow 1.8 scope and linking to this novel design document https://docs.google.com/document/d/1nGUvLonahoLogfWCHsoUOZl-s77YtPEiCjWBVlZjJHo/edit?usp=sharing

We use this document to discuss Phase 2 with the KFP community (related to https://github.com/kubeflow/pipelines/issues/8660).

**Comment by kimwnasptd** [comment]
Thanks @pranavpandit1! I also took a look on how to get these to work, when fixing the workflows for the CentralDashboard. You can take a look at this PR and some comments https://github.com/kubeflow/kubeflow/pull/6961

**Comment by kimwnasptd** [comment]
@lehrig I think we bumped into a side-effect that I hadn't thought about initially. Building the images in the GH Actions (which is doing virtualization via QEMU) is actually slow. 

Looking at an open PR https://github.com/kubeflow/kubeflow/pull/7060 that touches some web apps I see the following:
1. The workflow that builds for both platforms (VWA) takes 61minutes (!)
2. The workflow that builds with the old way (TWA) takes 9mins
![image](https://user-images.githubusercontent.com/11134742/227577044-90be1889-7c87-4051-8495-b1c59900ebbd.png)

The difference is huge, so I want to re-evaluate the approach of building for ppc64le when PRs are opened. 

From your experience, when is it most probable for the x86 build to succeed but for the ppc64le to fail?

**Comment by lehrig** [comment]
@kimwnasptd yeah, I agree that this is suboptimal. The answer is obviously "it depends", however, I think we have some hard evidence here that we should not proceed as originally planned. I see the following options for builds on PR opened.

1. Exclude non-x86 archs as long as native hardware is unavailable.
2. Exclude non-x86 archs only if building them takes too long.
3. Wait for native ppc64le out-of-the-box support for GHA, which hopefully comes this year (and this will not slow-down builds as emulation is not used).
4. Integrate a GitHub app connecting the GHA builds to native hardware we can provision via VMs.
5. (not sure this is technically possible; @pranavpandit1? @adilhusain-s?) Start the ppc64le QEMU-build asynchonously & don't let the PR wait for ppc64le build completion, so it doesn't block.

Note: Options 1, 2 & 5 are based on my observation that ppc64le is typically error-free when x86 builds without errors. Hence, we can typically accept PRs when only x86 builds. Rare corner cases are then discovered on PR merge.

If exclusion (options 1 or 2) is OK, I'd go for this option & later migrate to option 3 once native ppc64le GHA support becomes available later this year. Option 4 is possible but would require some additional efforts and organization on our side; so I see it only as a backup option. For option 5, I'd like to hear opinions from my team...

**Comment by lehrig** [comment]
Here are some stats that help getting a feeling for those options:

### Notebook-controller build
- Native ppc64le: 2.2 min
- QEMU ppc64le: 12 min and 47sec
- Native x86: 2 min and 6 sec

### Volume-web-app build
- Native ppc64le: 8.21 min
- QEMU ppc64le: 36 min and 35sec
- Native x86: 6 min and 56 sec

### Central-dashboard build
- Native ppc64le: 3.22 min
- QEMU ppc64le: 10 min and 26sec
- Native x86: 1 min and 55 sec

**Comment by lehrig** [comment]
I discussed the options with the team. Here is our proposal:
- On PR opened, we recommend option 2: only build PRs if they don't take too long and otherwise disable ppc64le builds like we showcase in https://github.com/DSpace/dspace-angular/pull/1667
- Looking at above stats, we believe "not too long" holds for all builds <= 30 min.
- As soon as option 3 becomes available, migrate all workflows to this option: run everything natively and enable it for all PR opened.
- On PR merged, we recommend to always build all supported architectures.
- We also recommend to generally improve build performance by enabled caching during builds, which will generally lower building times by 30-40%: https://github.com/kubeflow/kubeflow/issues/7072. If that is enabled, we will get more components under the 30 min. threshold.

@kimwnasptd, does that sound good? What do you think about the 30 min. threshold?

**Comment by lehrig** [comment]
Still have to answer this:
> From your experience, when is it most probable case for the x86 build to succeed but for the ppc64le to fail?
Seldomly happens once ppc64le support is there. The only case that is a bit harder  are new 3rd-party dependencies, for example, additional python wheels unavailable on ppc64le (wheels are thus in Phase 3 of this endeavor). With Go/Java/JS code we typically don't see these kind of issues as they are more architecturally independent than then Python ecosystem.

**Comment by kimwnasptd** [comment]
@lehrig thangs for the detailed explanation! I agree with your proposal and rationale. So my current understanding is the following, but please tell me if I miss something:
1. We can skip building multi-platform images when testing PRs, since we don't expect any issues
2. Build for all architectures when a PR is merged, and GHA build and publish images
3. Once we have native ppc64le support for GHA out-of-the-box we can migrate the workflows to use it

At the same time we can also work on caching in parallel https://github.com/kubeflow/kubeflow/issues/7072. Also if we in the future we see that there are a lot of issues when building/pushing the images between architectures we can then come back to evaluating building multi-arch images during opened PRs.

**Comment by lehrig** [comment]
Updated list of integrations by expanding phases & adding some smaller images for KServe + Katib. KFP is still moving slowly as it builds in another CI system, so we will first focus on KServe and Katib more.

**Comment by andreyvelich** [comment]
Let's continue this discussion in the community repo.
/transfer community
